### PR TITLE
Add value "get" function

### PR DESCRIPTION
**Pull request by calebmer**
This adds a new get function for value and depends on #9.

### CODE REVIEW

**Comment by svmnotn** [comment]
Just as a note, if it depends on #9 why not just pr into #9 instead?

**Comment by calebmer** [comment]
We are already sad that #9 is a big PR 😊

**Comment by calebmer** [comment]
It reads like a sentence 😊

**Comment by calebmer** [comment]
Rebased and force pushed so we lost some of our conversation, oops 😖

Is there a way to avoid that?

**Comment by svmnotn** [comment]
Never rebase on a public branch.

**Comment by calebmer** [comment]
Do you actually recommend doing that? I'd think rebasing is fine for any PR with the end result being a nice git history.

**Comment by svmnotn** [comment]
That is the '[golden rule](http://www.slideshare.net/lemiorhan/git-branching-model/22-Golden_Rule_Of_rebasing_Never)'.

**Pull request merged**
