### PR TITLE
Feat: error impl error

### PR DESCRIPTION
**Pull request by calebmer**

### CODE REVIEW

**Comment by svmnotn** [comment]
Fix imports

**Comment by calebmer** [comment]
Imports work fine for me…wait…I'm on nightly…

**Comment by svmnotn** [comment]
I'll just point out it was you that changed the .travis file...

**Comment by calebmer** [comment]
I thought I was on stable, I must have tried to do something on nightly then forgot to switch back.

**Comment by calebmer** [comment]
I prefer fast tests 😉

**Comment by calebmer** [comment]
Tests should pass now.

**Comment by calebmer** [comment]
Tests are passing, review plz.

**Pull request merged**
